
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.6.13
 * Fri Nov 12 11:39:07 GMT+01:00 2021
 * Generated source version: 2.6.13
 */

@XmlRootElement(name = "chercherResponse", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chercherResponse", namespace = "http://service/")

public class ChercherResponse {

    @XmlElement(name = "return")
    private model.NouveauNe _return;

    public model.NouveauNe getReturn() {
        return this._return;
    }

    public void setReturn(model.NouveauNe new_return)  {
        this._return = new_return;
    }

}

